spring:
  application:
    name: Bios

  profiles:
    group:
      local: "local"

  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        highlight_sql: true
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  #log
  logging:
    level:
      root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui