spring:
  application:
    name: Bios

  profiles:
    group:
      local: "local"

  #jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        highlight_sql: true # 색상 부여
        format_sql: true
        show_sql: true # hibernate sql 로그 활성화
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  #log
  logging:
    level:
      root: INFO